name: Build & Test

on:
  pull_request:

jobs:
  unit_tests:
    name: Run Unit Tests
    runs-on: docker
    container:
      image: git.wbrawner.com/wbrawner/docker/android:36
    steps:
      - uses: https://git.wbrawner.com/actions/checkout@v6
      - name: Run unit tests
        run: ./gradlew check
      - name: Publish JUnit Results
        uses: https://git.wbrawner.com/actions/upload-artifact@v3
        if: always()
        with:
          name: Unit Test Results
          path: "*/build/reports/*"
          if-no-files-found: error
  ui_tests:
    if: false
    runs-on: docker
    container:
      image: git.wbrawner.com/wbrawner/docker/android:36
    name: Run UI Tests
    needs:
      - unit_tests
    steps:
      - uses: https://git.wbrawner.com/actions/checkout@v6
      - name: Build APKs
        run: ./gradlew assemblePlayDebug assemblePlayDebugAndroidTest
      - name: Grant execute permission for flank_auth.sh
        run: chmod +x flank_auth.sh
      - name: Add auth for flank
        env:
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
        run: |
          ./flank_auth.sh
      - name: Run UI tests
        run: ./gradlew runFlank
